# Generated by Django 6.0.1 on 2026-02-03 09:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # --- DEPARTMENT MODEL ---
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        # --- USER MODEL ---
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[
                    ('ADMINISTRATOR', 'Administrator'),
                    ('CONSULTANT', 'Consultant'),
                    ('EXECUTIVE_DIRECTOR', 'Executive Director'),
                    ('COURSE_COORDINATOR', 'Course Coordinator'),
                    ('ACCOUNT_MANAGER', 'Account Manager'),
                    ('CENTRE_MANAGER', 'Centre Manager'),
                    ('OFFICER', 'Officer/Staff')
                ], default='OFFICER', max_length=30)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.department')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),

        # --- ACADEMIC STRUCTURE ---
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('yearNumber', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.Major')),
            ],
            options={'ordering': ['yearNumber'], 'unique_together': {('major', 'yearNumber')}},
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.Year')),
            ],
            options={'ordering': ['semester_number'], 'unique_together': {('year', 'semester_number')}},
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('academic_calendar_received', models.BooleanField(default=False)),
                ('timetable_received', models.BooleanField(default=False)),
                ('textbooks_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Major')),
            ],
        ),

        # --- STUDENT & ENROLLMENT ---
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('nrc', models.CharField(max_length=50)),
                ('student_phone_no', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Enrolled', max_length=20)),
                ('contract_signed', models.BooleanField(default=False)),
                ('id_card_ordered', models.BooleanField(default=False)),
                ('id_card_issued', models.BooleanField(default=False)),
                ('parent_present_at_induction', models.BooleanField(default=False)),
                ('student_present_at_induction', models.BooleanField(default=False)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Intake')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.Student')),
            ],
        ),

        # --- SOP DOCUMENT WORKFLOWS ---
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('REC', 'Recommendation'), ('TRN', 'Transcript'), ('CRT', 'Certificate')], max_length=3)),
                ('finance_approved', models.BooleanField(default=False)),
                ('admin_ref_number', models.CharField(blank=True, max_length=50)),
                ('is_collected', models.BooleanField(default=False)),
                ('date_ready', models.DateField(blank=True, null=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
        ),
        migrations.CreateModel(
            name='OverseasRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('waybill_number', models.CharField(max_length=100)),
                ('document_types', models.CharField(max_length=255)),
                ('received_from_partner_date', models.DateField()),
                ('scanned_copy', models.FileField(blank=True, null=True, upload_to='overseas_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Enrollment')),
            ],
        ),

        # --- NOTIFICATIONS ---
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]