# Generated by Django 6.0.4 on 2026-05-01 07:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def student_image_path(instance, filename):
    ext = filename.split('.')[-1]
    return f'students/{instance.school_id}/profile.{ext}'

def validate_file_size(value):
    filesize = value.size
    if filesize > 2 * 1024 * 1024:  # 2MB Limit
        from django.core.exceptions import ValidationError
        raise ValidationError("Maximum file size is 2MB")
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('EXAM', 'Exam'), ('PLANNING', 'Planning')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('desired_program', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('student_contact_no', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_contact_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('enquiry_type', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Walk-in', 'Walk-in'), ('Phone', 'Phone'), ('Facebook', 'Facebook')], max_length=20)),
                ('source_of_information', models.CharField(choices=[('Friend', 'Friend'), ('Facebook', 'Facebook'), ('Pamphlet', 'Pamphlet'), ('Newspaper', 'Newspaper'), ('Others', 'Others')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Dropout', 'Dropout'), ('Graduated', 'Graduated'), ('Interrupted', 'Interrupted')], default='Enrolled', max_length=20)),
                ('enrolled_date', models.DateField()),
                ('scholar', models.BooleanField(default=False)),
                ('registration_fee', models.BooleanField(default=False)),
                ('first_installment_fee', models.BooleanField(default=False)),
                ('nrc_copy', models.BooleanField(default=False)),
                ('census_copy', models.BooleanField(default=False)),
                ('passport_photo', models.BooleanField(default=False)),
                ('education_certificate', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        
        # 1. Create the Subject model first
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('yearNumber', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.major')),
            ],
            options={
                'ordering': ['yearNumber'],
                'unique_together': {('major', 'yearNumber')},
            },
        ),

        # 2. Create the Semester model
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.year')),
            ],
            options={
                'ordering': ['semester_number'],
                'unique_together': {('year', 'semester_number')},
            },
        ),

        # 3. Create the Junction table (SemesterSubject)
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('semester', 'subject')},
            },
        ),
        # 4. Add the ManyToMany relationship to Semester using the 'through' table
        migrations.AddField(
            model_name='semester',
            name='subjects',
            field=models.ManyToManyField(related_name='semesters', through='core.SemesterSubject', to='core.Subject'),
        ),

        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=255, unique=True)),
                ('profile_image', models.ImageField(
                    blank=True, 
                    null=True, 
                    upload_to=student_image_path,
                    validators=[validate_file_size]
                )),
                ('full_name', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nrc', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('student_phone_no', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('referral_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('activities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dropout',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('dropout_date', models.DateField()),
                ('followup_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropout_record', to='core.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpSession',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('handled_by', models.CharField(max_length=255)),
                ('walkup_followup', models.BooleanField(default=False)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.enquiry')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.intake'),
        ),
        migrations.AddField(
            model_name='intake',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='core.major'),
        ),
        migrations.AddField(
            model_name='intake',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_intakes', to='core.semester'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(default='FOLLOW_UP', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student'),
        ),    
        migrations.CreateModel(
            name='ReportEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_mentions', to='core.enquiry')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_enquiries', to='core.dailyreport')),
            ],
            options={
                'verbose_name_plural': 'Report enquiries',
                'unique_together': {('report', 'enquiry')},
            },
        ),
        # migrations.CreateModel(
        #     name='RolePermission',
        #     fields=[
        #         ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
        #         ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('module', models.CharField(max_length=50)),
        #         ('action', models.CharField(max_length=20)),
        #         ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
        #     ],
        #     options={
        #         'verbose_name': 'Role Permission',
        #         'verbose_name_plural': 'Role Permissions',
        #         'unique_together': {('role', 'module', 'action')},
        #     },
        # ),
        migrations.CreateModel(
            name='IntakeSemester',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_semesters', to='core.intake')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('intake', 'semester')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'semester_number')},
        ),
    ]
