# Generated by Django 6.0.5 on 2026-05-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_semester_options_alter_exampaper_question_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresultsharelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
